stages:
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/raw/train.csv
    params:
      - train
      - model
    outs:
      - models/staging/model.pkl
    metrics:
      - metrics/train_metrics.json:
          cache: false

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/staging/model.pkl
      - data/raw/train.csv
    params:
      - train
    metrics:
      - metrics/eval_metrics.json:
          cache: false

  promote:
    cmd: python scripts/promote.py
    deps:
      - scripts/promote.py
      - models/staging/model.pkl
      - metrics/eval_metrics.json
    params:
      - promote
    outs:
      - models/production/model.pkl
