train:
  test_size: 0.2
  random_state: 42

model:
  n_estimators: 100
  max_depth: 5
  random_state: 42

promote:
  min_accuracy: 0.85
  staging_model: models/staging/model.pkl
  production_model: models/production/model.pkl
